function loadDashboardContent() {
    return `
         <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">1. Cases</h3>
          <p>Overview of settled cases, Unsettled cases, and pending cases.</p>
          <img class="w-[40rem]" src="user_manual_pic/casess.png" alt="cases picture">
        </section>

        <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">2. References and Links</h3>
          <p>Overview of references and links related to EKP.</p>
          <img class="w-[40rem]" src="user_manual_pic/references_links.png" alt="references and links picture">
        </section>
    `;
}

function loadComplaintContent() {
    return `
        <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">1. Complaint</h3>
          <p>An overview of complaints is provided. The border color of the table column will change based on the status of cases. You can also add, edit, manage, or archive cases.</p>

          <section class="flex gap-x-1 items-center">
            <div class="h-[1rem] w-[1rem] rounded-full bg-green-500"></div>
            <p>for settled cases</p>
          </section>
          <section class="flex gap-x-1 items-center">
            <div class="h-[1rem] w-[1rem] rounded-full bg-yellow-500"></div>
            <p>for pending cases(10-14 days)</p>
          </section>
          <section class="flex gap-x-1 items-center">
            <div class="h-[1rem] w-[1rem] rounded-full bg-red-500"></div>
            <p>for Unsettled cases(15-30 days)</p>
          </section>

          <img class="w-[50rem]" src="user_manual_pic/complaint.png" alt="complaint picture">

          <p>1. Add Complaint</p>
          <p>The "Case No" field is auto generated by the system, so you don't need to enter it.</p>
          <p>For the "For" field, you can choose from the dropdown that is already provided or type what the complaint is.</p>
          <p>After all the fields has filled out, click the "Submit" button to submit the case.</p>
          <img class="w-[40rem]" src="user_manual_pic/add_complaint.png" alt="add complaint picture">

          <p>2. Edit Complaint</p>
          <p>Here, every field is editable. To update the modifications you made, click the "Update" button.</p>
          <img class="w-[40rem]" src="user_manual_pic/edit_complaint.png" alt="edit complaint picture">

          <p>3. Archive Complaint</p>
          <p>All the archived complaints will go to the archive page.</p>

          <p>4. Manage Complaint</p>
          <img class="w-[40rem]" src="user_manual_pic/manage_complaint.png" alt="manage complaint picture">
          <p>You can add hearing, used kp form from 7 to 25. You cna also print, download, or save it</p>
          <p>All the used form will appear to Used Forms section.</p>
          <p>All the forms that are signed by the respective official (ex: punong barangay) go to the Signed Forms section.</p>
        </section>
    `;
}

function loadArchiveContent() {
    return `
        <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">1. Archive</h3>
          <p>Here are all of the cases you have archived. By checking the box and then clicking the "Unarchive" button, you can unarchive them. Additionally, you may use the search bar to look for particular cases.</p>
          <img class="w-[40rem]" src="user_manual_pic/archive.png" alt="archive picture">
        </section>
    `;
}

function loadLTIAContent() {
    return `
        <section class="w-full text-center">
          <p>No data yet!</p>
        </section>
    `;
}

function loadLuponContent() {
    return `
         <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">1. KP forms</h3>
          <p>You can use kp form 1 to 6 either english or tagalog.</p>
          <img class="w-[40rem]" src="user_manual_pic/kp1_6.png" alt="archive picture">
          <p>1. Example of tagalog kp form 5</p>
          <p>It can be saved, downloaded, or printed. When saved, it will appear in the "Used Forms" section.</p>
          <img class="w-[40rem]" src="user_manual_pic/kp5_sample.png" alt="tagalog kp5 picture">

          <h3 class="text-[2rem]">2. Used Forms</h3>
          <p>Here are all of the kp forms that have been utilized. You may search by year as well.</p>
          <img class="w-[40rem]" src="user_manual_pic/used_form.png" alt="used form picture">

          <h3 class="text-[2rem]">3. Lupon</h3>
          <p>Punong barangay, lupon chairman, and up to 20 lupon can be added. Additionally, you can upload files, clear all, notice, or appoint for Lupon.</p>
          <img class="w-[40rem]" src="user_manual_pic/lupon.png" alt="lupon picture">

          <h3 class="text-[2rem]">4. Upload file for lupon</h3>
          <p>An overview of the interface for lupon file uploading.</p>
          <img class="w-[40rem]" src="user_manual_pic/uploadfile_lupon.png" alt="upload file for lupon picture">
        </section>
    `;
}

function loadSettingContent() {
    return `
        <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">1. Update Information</h3>
          <p>You can update your information, such as profile picture, username, first name, last name, etc. Live the password field empty to keep the current password.</p>
          <img class="w-[20rem]" src="user_manual_pic/account_setting.png" alt="account setting picture">
        </section>

        <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">2. Update Security Setting</h3>
          <p>You can update the three answers and questions that you have provided last time</p>
          <img class="w-[20rem]" src="user_manual_pic/security_setting.png" alt="security setting picture">
        </section>

        <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">3. Update LGU or KP logo.</h3>
          <p>You can update the LGU or KP logo. Click the "upload" button, choose the photo you desire, and then click "save.</p>
          <img class="w-[20rem]" src="user_manual_pic/LGUKP_logo.png" alt="LGU and KP logo picture">
        </section>
    `;
}

function loadUserlogContent() {
    return `
         <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">1. Cases</h3>
          <p>Overview of dates and times the user has logged in.</p>
          <img class="w-[40rem]" src="user_manual_pic/userlog.png" alt="userlog picture">
        </section>
    `;
}

function loadReportContent() {
    return `
        <section class="flex flex-col gap-y-2">
          <h3 class="text-[2rem]">1. Report Overview</h3>
          <img class="w-[40rem]" src="user_manual_pic/report_overview.png" alt="report overview picture">
        </section>
    `;
}







